
server:
  port: 8080

spring:
  application:
    name: AI Youtube Thumbnail Generator - Spring Boot
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.thumbnail.generator: DEBUG

gemini:
  api:
    key: ${GEMINI_API_KEY:your_gemini_api_key}
    endpoint: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image-preview:generateContent
